method et test
B4va/alternbot-app pull request #70
Opened 2021-02-19 13:24 UTC by alexisbe-github

2021-02-19 13:25 UTC, alexisbe-github commented
Je me suis appuyé sur le code de suppression d'une task.

2021-02-19 15:27 UTC, B4va requested changes

2021-02-19 15:27 UTC, B4va commented on src/test/java/process/data/TestTaskCreationProcess.java
> +        Role validRole = mock(Role.class);
Est-ce que ça te parle plus l'utilisation des mocks mtn ? :)

2021-02-19 15:27 UTC, B4va commented on src/main/java/process/data/TaskCreationProcess.java
> +    public boolean create(Task task,Member member, Server server) throws ServerAccessException, MemberAccessException {
Ici je dirais qu'il serait plus simple de prendre comme argument les attributs de la task au format dans lequel ils seront dans la commande et de l'instancier dans le process.

Je pense également qu'il faudrait valider les attributs de la task avant de l'enregistrer : vérifier notamment que les attributs ne sont pas vides ou nulls.

> Possible d'extraire l'instanciation et la validation de la task dans une méthode privée : 

```
private Task validateTask(String description, String dueDate, String dueTime) throws InvalidDataException
```

> La méthode publique du process aurait donc finalement le profil suivant :

```
public boolean create(String description, String dueDate, String dueTime, Member member, Server server) throws ServerAccessException, MemberAccessException, InvalidDataException
```

2021-02-19 16:31 UTC, alexisbe-github commented on src/test/java/process/data/TestTaskCreationProcess.java
> +        Role validRole = mock(Role.class);
Oui effectivement :D

2021-02-21 11:38 UTC, zacharyarnaise commented on src/main/java/process/data/TaskCreationProcess.java
> +import com.sun.media.sound.InvalidDataException;
Peut être que ce serait mieux d'implémenter une classe `InvalidDataException` dans le package `exceptions` de l'app, de la même manière que ce qui a été fait pour `MemberAccessException` et `ServerAccessException` ?

2021-02-21 13:53 UTC, B4va requested changes

2021-02-21 13:53 UTC, B4va commented on src/test/java/process/data/TestTaskCreationProcess.java
> +public class TestTaskCreationProcess {
Je propose l'ajout de 3 tests :

- si le serveur n'a pas accès à la task > renvoi d'une erreur ServerAccessException
- si l'utilisateur n'est pas habilité > renvoi d'une erreur MemberAccessException
- si la tâche est invalide > renvoi d'une erreur InvalidDataException

2021-02-21 13:53 UTC, B4va commented on src/main/java/process/data/TaskCreationProcess.java
> +import com.sun.media.sound.InvalidDataException;
Oui je suis d'accord

2021-02-28 13:49 UTC, B4va approved these changes

2021-02-28 13:49 UTC, merged